services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - GO_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=sentinel_auth
      - API_ADDR=0.0.0.0:8080
      - ROOT_CLIENT_ID=995b8108-a26d-4ac7-bd1e-faa5efa47e48
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # auth-client-lib:
  #   build:
  #     context: ./frontend/lib
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend/lib:/app
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run build

  auth-frontend:
    build:
      context: ./frontend
      dockerfile: ./sentinel-auth-signin/Dockerfile.auth
      args:
        - NEXT_PUBLIC_SENTINEL_API_URL=http://104.248.57.142:8080/v1
        - NEXT_PUBLIC_SENTINEL_UI_URL=http://104.248.57.142:3000
        - NEXT_PUBLIC_SENTINEL_CLIENT_ID=995b8108-a26d-4ac7-bd1e-faa5efa47e48
        - NEXT_PUBLIC_SENTINEL_REDIRECT_URI=http://localhost:3000/auth
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/sentinel-auth-signin:/app/frontend/sentinel-auth-signin
      - ./frontend/lib:/app/frontend/lib
      - /app/frontend/sentinel-auth-signin/node_modules
    environment:
      - NEXT_PUBLIC_SENTINEL_API_URL=http://104.248.57.142:8080/v1
      - NEXT_PUBLIC_SENTINEL_UI_URL=http://104.248.57.142:3000
      - NEXT_PUBLIC_SENTINEL_CLIENT_ID=995b8108-a26d-4ac7-bd1e-faa5efa47e48
      - NEXT_PUBLIC_SENTINEL_REDIRECT_URI=http://localhost:3000/auth
    depends_on:
      - api
    restart: unless-stopped

  example-frontend:
    build:
      context: ./frontend
      dockerfile: ./sentinel-example/Dockerfile.example
      args:
        - NEXT_PUBLIC_SENTINEL_API_URL=http://104.248.57.142:8080/v1
        - NEXT_PUBLIC_SENTINEL_UI_URL=http://104.248.57.142:3000
        - NEXT_PUBLIC_SENTINEL_CLIENT_ID=995b8108-a26d-4ac7-bd1e-faa5efa47e48
        - NEXT_PUBLIC_SENTINEL_REDIRECT_URI=http://localhost:3000/auth
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/sentinel-example:/app/frontend/sentinel-example
      - ./frontend/lib:/app/frontend/lib
      - /app/frontend/sentinel-example/node_modules
    environment:
      - NEXT_PUBLIC_SENTINEL_API_URL=http://104.248.57.142:8080/v1
      - NEXT_PUBLIC_SENTINEL_UI_URL=http://104.248.57.142:3000
      - NEXT_PUBLIC_SENTINEL_CLIENT_ID=995b8108-a26d-4ac7-bd1e-faa5efa47e48
      - NEXT_PUBLIC_SENTINEL_REDIRECT_URI=http://localhost:3000/auth
    depends_on:
      - api
    restart: unless-stopped

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: sentinel_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:5050"
    depends_on:
      - db

volumes:
  pgdata:
