# Assuming Docker context is the repo root

FROM node:22-alpine

WORKDIR /app

# ---- Build shared library ----
WORKDIR /app/lib
COPY lib/package*.json ./
RUN npm install
COPY lib .
RUN npm run build
RUN npm link

# ---- Build sentinel-example app ----
WORKDIR /app/sentinel-example
COPY sentinel-example/package*.json ./
RUN npm install
RUN npm link sentinel-auth-client-js

COPY sentinel-example/.env* ./

COPY sentinel-example .
RUN npm run build

EXPOSE 3001

COPY sentinel-example/docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["npm", "run", "start"]
